USE [PEDIDOS]

GO 

/*
1. REALIZAR UNA CONSULTA GENERAL DE CLIENTES 
*/
SELECT * FROM CLIENTES

/*2. MOSTRAR EL CLIENTE CUYO IDENTIFICACION ES LA SIGUIENTE: 1845677777		EL REPORTE DEBERA SALIR DE LA SIGUIENTE MANERA:			CODIGO_CLIENTE			CEDULA_RUC			NOMBRE_CIA			NOMBRE_CONTACTO*/
SELECT CLIENTEID,CEDULA_RUC, NOMBRECIA, NOMBRECONTACTO FROM [dbo].[CLIENTES]
WHERE CEDULA_RUC ='1845677777'

/*	3. Obtener la minima existencia y maxima existencia de todos los productos	EL REPORTE DEBERA SALIR DE LA SIGUIENTE MANERA:	CODIGO PRODUCT	DESCRIPCION	MIN_EXISTENCIA	MAX_EXISTENCIA*/

SELECT [PRODUCTOID],[DESCRIPCION],
    (SELECT MAX([EXISTENCIA])
     FROM [dbo].[PRODUCTOS] AS A
     WHERE A.PRODUCTOID= B.PRODUCTOID) AS MAX_EXISTENCIA,
	 (SELECT MIN([EXISTENCIA])
     FROM [dbo].[PRODUCTOS] AS C
     WHERE C.PRODUCTOID= B.PRODUCTOID) AS MIN_EXISTENCIA

FROM [dbo].[PRODUCTOS] AS B;

/*	4.  REALIZAR UNA SUBCONSULTA EN LA TABLA PRODUCTOS, EN LA CUAL SE DEBERA PRESENTAR		EL NOMBRE DEL PROVEEDOR Y NOMBRE DE LA CATEGORIA		EL REPORTE DEBERA QUEDAR DE LA SIGUIENTE MANERA:			CODIGO_PRODUCTO			DESCRIPCION			CODIGO_PROVEEDOR			NOMBRE_PROVEEDOR			CATEGORIA_ID			NOMBRE_CATEGORIA*/
SELECT
	PRODUCTOID AS CODIGO_PRODUCTO,
	DESCRIPCION,
	(SELECT PROVEEDORID FROM [dbo].[PROVEEDORES] AS C
		WHERE C.PROVEEDORID=A.PROVEEDORID) AS CODIGO_PROVEEDOR,
	(SELECT NOMBREPROV FROM [dbo].[PROVEEDORES] AS D
		WHERE D.PROVEEDORID=A.PROVEEDORID) AS NOMBRE_PROVEEDOR,
	(SELECT CATEGORIAID FROM CATEGORIAS AS E
		WHERE E.CATEGORIAID=A.CATEGORIAID) AS CATEGORIA_ID,
	(SELECT NOMBRECAT FROM CATEGORIAS AS B
		WHERE B.CATEGORIAID=A.CATEGORIAID) AS NOMBRE_CATEGORIA
FROM PRODUCTOS AS A/*	5. OBTENER LOS 5 MEJORES PRODUCTOS EN FUNCION DE SU PRECIO UNITARIO*/SELECT TOP 5 * FROM [dbo].[PRODUCTOS]ORDER BY PRECIOUNIT DESC/*	6. OBTENER LA SUMATORIA DE TODAS LAS EXISTENCIAS DE LA TABLA PRODUCTOS.*/SELECT SUM(EXISTENCIA) AS Total_Existencias FROM [dbo].[PRODUCTOS];